# Generated by Django 2.2.5 on 2020-04-19 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_imagecollector_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollector',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
