# Generated by Django 2.2.5 on 2020-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_imagecollector_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollector',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
