# Generated by Django 2.2.5 on 2020-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='ultrasound',
            field=models.ImageField(upload_to='ultrasound/'),
        ),
    ]
