# Generated by Django 2.2.5 on 2020-04-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200410_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_data',
        ),
    ]
